---
title: "FFT"
output: 
  html_notebook:
    code_folding: hide
runtime: shiny
---

```{r include=FALSE}
library(tidyverse)
library(magrittr)
library(zeallot)
library(cowplot)
library(plotly)
library(shiny)
library(janitor)
library(dplR)
library(levi)
library(seewave)
library(fBasics)
library(lobstr)
library(rlang)
```

```{r}
fluidRow(
column(width = 10,
       textInput("signal", "Signal", width = "100%", 
          value = "100 * exp(-.5 * t) * (sin(2 * pi * (30 - (0.5)*t) * t))")),
column(width = 2, numericInput("noise", "Signal-Noise", value = 30, min = 0, max = 100, step = 1))
)



fluidRow(
  column(width = 2, actionButton("resample", "resample")), 
  column(width = 2, numericInput("sr", "Sample-Rate", value = 100, min = 0, max = 400)),
  column(width = 2, numericInput("T", "Frame-Size", value = 1, min = 0, max = 10)),
  column(width = 2, numericInput("lp", "Low-Pass", min = 0, max = 400, value = 0)),
  column(width = 2, numericInput("hp", "high-Pass", min = 0, max = 400, value = 400))
)

observeEvent(input$sr, updateNumericInput(session, "hp", value = input$sr/2, max = input$sr/2))
ex_data <- 
reactive({
  input$resample
  gen_example_data(
      T = input$T,
      sr = input$sr,
      signal = input$signal,
      noise_sd = input$noise
    )
})
renderPlot({
  input$resample
  sr <- input$sr
  ex_data <- ex_data()

  sig_plot <- 
    ex_data %>% 
    ggplot(aes(x = t, y = s)) + geom_line() +
    geom_line(aes(y = seewave::env(s, f = input$sr, plot = FALSE)), color = "blue") +
    geom_line(aes(y = seewave::env(s, f = input$sr, envt = "abs", plot = FALSE)), color = "green")
  
  # calculate fc
  bp_values = tibble(cut = c(input$lp, input$hp, sr-input$hp, sr-input$lp))
  sig_fc <- levi::fftc(ex_data, "s", sr)
  
  fcp <- 
    sig_fc %>% 
    ggplot(aes(x = f)) +
    geom_vline(data = bp_values, aes(xintercept = cut)) + 
    xlim(c(input$lp, input$hp))
  
  # bp filter
  bp_signal <- levi::bp_filter(ex_data, "s", bp = c(input$lp, input$hp), sr)
  sig_plot <-
    sig_plot + geom_line(data = bp_signal, aes(x = t, y = s), color = "red")
  
  # max amplitude
  c(f_max, fmax_amp) %<-% get_dom_freq(sig_fc, sr)
  #print(sr)
  c(fit_params, fitted, model, ...) %<-%
    (ex_data %>%
       fftc("s", sr) %>%
       dplyr::filter(between(f, input$lp, input$hp)) %>%
       fit_lorentz(sr = sr))
    
  # visualize
  fcp <-
    fcp + 
    geom_point(aes(y = fc_amp)) +
    geom_point(data = fitted, aes(x = f, y = lf_amp), color = "red") +
    geom_line(data = tibble(f = seq(10, 70, by = .01), lf_amp = sqrt(predict(model, newdata = list(f = f)))),
              aes(x = f, y = lf_amp), color = "red") +
    geom_vline(xintercept = fit_params$estimate[2], color = "red") + 
    labs(subtitle = str_glue("f={round(f_max, 2)}Hz/ Amp = {2 * round(fmax_amp, 1)} 
                              f= {round(fit_params$estimate[2], 2)}Hz/ d={round(fit_params$estimate[3], 2)}Hz"))
  
  plot_grid(
    sig_plot, 
    fcp, 
    nrow = 2)
})

renderPlot({
  ex_data <- ex_data()
  spectrum(ts(ex_data$s, frequency = input$sr))
})

renderPlot({
 spectro(ex_data()$s, f=input$sr, wl = nextn(floor(input$sr), factors = c(2))/4, ovlp = 50, osc = TRUE, 
         flim = c(input$lp, input$hp - 1)/1000)
 # par(new=TRUE)
 # dfreq(ex_data()$s, f=input$sr, wl = nextn(floor(input$sr), factors = c(2))/4, ovlp=50, threshold=10, 
 #       bandpass = c(input$lp, input$hp - 1), 
 #       type="l", col="black", lwd=4)
 })

```

Folgerungen:

Sieht so aus als würde die Dämpfung systematisch um einen Faktor 10 *unterschätzt*
werden! Eine Verbreiterung der Lorentzkurve (hier also des Periodogramms) sollte aber 
dazu führen das die Dämpfung überschätzt wird!
 
Wie lässt sich das erklären? Das theoretisch Spektrum sollte durch das Fejer-Fenster 
verbreitert werden. 

Ich glaube der Punkt ist: 
